server:
  port: 8082

spring:
  application:
    name: itcasst-microservice-order #指定服务名

eureka:
  client:
    registerWithEureka: true #是否将自己注册到Eureka服务中，默认为true
    fetchRegistry: true #是否从Eureka中获取注册信息，默认为true
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://admin:admin@127.0.0.1:8083/eureka/,http://admin:admin@127.0.0.1:8084/eureka/
  instance:
    prefer-ip-address: true #将自己的ip地址注册到Eureka服务中

feign:
  hystrix:
    # feign熔断器开关
    enabled: true
